# Sample application.yml for Sushil POC Trade Store
# Copy this file to application.yml and fill in your real secrets locally.

spring:
  datasource:
    url: jdbc:mysql://<HOST>:<PORT>/<DB_NAME>?ssl-mode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <DB_USERNAME>
    password: <DB_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://<MONGO_HOST>:<MONGO_PORT>/<MONGO_DB>

# Add any other required secrets or config here
