@startuml

class Trade {
  - String tradeId
  - int version
  - String counterPartyId
  - String bookId
  - LocalDate maturityDate
  - LocalDate createdDate
  - String expired
}

Trade "*" -- "1" TradeStore : stores

@enduml
